import {findDelegateCycle,rangesOverlap,checkApprovalMatrix} from '../src/domain/validation';
import type {ApprovalMatrixEntry,FlowNode,Role} from '../src/types';
const M=(id:string,label:string,role:string,min:number,max:number|null,delegateRole:string):ApprovalMatrixEntry=>({nodeId:id,nodeLabel:label,role,range:{min,max},delegateRole});
const mk=(ms:ApprovalMatrixEntry[]):FlowNode[]=>ms.map(m=>({id:m.nodeId,type:'approval',position:{x:0,y:0},data:{label:m.nodeLabel,state:'valid',config:{approverSource:'固定角色',role:m.role,min:m.range.min,max:m.range.max,delegateRole:m.delegateRole}}}));
const roles:Role[]=[{id:'a',name:'A',status:'active'},{id:'b',name:'B',status:'active'},{id:'c',name:'C',status:'active'},{id:'d',name:'D',status:'active'}];
let ok=0,bad=0;
const check=(name:string,pass:boolean)=>{console.log((pass?'PASS ':'FAIL ')+name);pass?ok++:bad++;};
check('边界相接不重叠',rangesOverlap({min:0,max:3000},{min:3000,max:8000})===false);
check('无上限区间重叠',rangesOverlap({min:50000,max:null},{min:0,max:60000})===true);
let cyc=findDelegateCycle([M('1','n1','A',0,100,'B'),M('2','n2','B',0,100,'A')]);
check('A→B→A 成环',cyc.length===2&&cyc.includes('A')&&cyc.includes('B'));
cyc=findDelegateCycle([M('1','n1','A',0,100,'B'),M('2','n2','B',0,100,'C'),M('3','n3','C',0,100,'D')]);
check('直链不成环',cyc.length===0);
cyc=findDelegateCycle([M('1','n1','A',0,100,'A')]);
check('自环 A→A',cyc.length===1&&cyc[0]==='A');
cyc=findDelegateCycle([M('1','n1','A',0,100,'C'),M('2','n2','B',0,100,'C'),M('3','n3','C',0,100,'D')]);
check('共尾分叉不成环',cyc.length===0);
cyc=findDelegateCycle([M('1','n1','A',0,100,'B'),M('2','n2','B',0,100,'A'),M('3','n3','C',0,100,'D'),M('4','n4','D',0,100,'C')]);
check('两个不相交环均检出',cyc.length===4);
const depRoles:Role[]=[...roles,{id:'x',name:'X',status:'departed'}];
const conflict=mk([M('1','小额','A',0,5000,'B'),M('2','中额','A',3000,20000,'B'),M('3','采购','B',0,10000,'A')]);
const nodes2=[...conflict,mk([M('4','离职','X',1,2,'A')])[0]];
const {issues}=checkApprovalMatrix(nodes2,depRoles);
const kinds=issues.filter(i=>i.level==='error').map(i=>i.kind);
check('区间重叠阻断',kinds.includes('matrix-overlap'));
check('代理成环阻断',kinds.includes('matrix-cycle'));
check('离职未交接阻断',kinds.includes('matrix-departed'));
const overlapIssue=issues.find(i=>i.kind==='matrix-overlap')!;
check('重叠区间为 ¥3,000~¥5,000',overlapIssue.conflictNodeId==='2'&&overlapIssue.message.includes('¥3,000 ~ ¥5,000'));
const {issues:w2}=checkApprovalMatrix(mk([M('1','n','X',1,2,'A')]),[{id:'x',name:'X',status:'departed',handoverTo:'A'}]);
check('离职已交接仅警告',w2.length===1&&w2[0].level==='warning');
console.log(`\n${ok} passed, ${bad} failed`);
if(bad) throw new Error(`${bad} domain checks failed`);
