import {useEffect,useState} from 'react'; import {useNavigate,useParams} from 'react-router-dom';import {ArrowLeft,CheckCircle2,ChevronDown,Eye,FileClock,Grid3x3,Lock,Play,Plus,Save,Send,Snowflake,Trash2,XCircle} from 'lucide-react'; import {FlowCanvas} from '../components/FlowCanvas'; import {ReasonModal} from '../components/ReasonModal';import {useAppStore} from '../store/useAppStore'; import {rangeText} from '../domain/validation';import type {FlowNode,NodeKind} from '../types';
const palette:[NodeKind,string,string][]=[['start','开始','流程入口'],['form','表单填写','收集业务数据'],['approval','审批','人工审批任务'],['condition','条件分支','按规则分流'],['automation','自动化','执行本地动作'],['notify','通知','发送站内通知'],['end','结束','流程终点']];
export function Editor(){const {id}=useParams(),nav=useNavigate();const store=useAppStore();const w=store.workflows.find(x=>x.id===id)||store.workflows.find(x=>x.id===store.currentId)||store.workflows[0];const selected=w.nodes.find(n=>n.id===store.selectedNodeId);useEffect(()=>{if(id&&id!==store.currentId)store.setCurrent(id)},[id]);useEffect(()=>{if(store.pendingValidate){store.runValidation();store.clearPendingValidate()}},[store.currentId]);const [askAdjust,setAskAdjust]=useState(false);
const locked=w.status==='published'||w.status==='archived';
const add=(type:NodeKind)=>{if(locked)return;const node:FlowNode={id:type+'-'+Date.now(),type,position:{x:350+Math.random()*200,y:200+Math.random()*150},data:{label:palette.find(x=>x[0]===type)![1],state:'unconfigured',config:{}}};store.updateNodes([...w.nodes,node])};
const publish=()=>{if(locked){setAskAdjust(true);return}store.publish()};
const indicator={draft:['● 草稿','draft-indicator'],adjusting:['◐ 调整草稿 · 基于 v'+w.baseVersion,'adjust-indicator'],published:['✓ 已发布 · v'+w.version+' 快照已冻结','frozen-indicator'],archived:['■ 已归档 · v'+w.version+' 快照已冻结','frozen-indicator']} as const;
return <div className="editor-page"><div className="editor-top"><button className="icon-btn" onClick={()=>nav('/workflows')}><ArrowLeft/></button><div className="editor-title"><small>流程管理 / {w.domain}</small><b>{w.name}</b></div><span className={indicator[w.status][1]}>{indicator[w.status][0]}</span><div className="editor-actions"><button className="secondary" onClick={()=>nav(`/workflows/${w.id}/matrix`)}><Grid3x3/>审批矩阵</button><button className="secondary" onClick={store.save} disabled={locked}><Save/>保存草稿</button><button className="secondary" data-testid="validate-button" onClick={store.runValidation}><Play/>运行校验</button><button className="secondary" onClick={()=>nav(`/workflows/${w.id}/preview`)}><Eye/>预览</button><button className="secondary" onClick={()=>nav(`/workflows/${w.id}/versions`)}><FileClock/>版本历史</button>{locked?<button data-testid="adjust-button" onClick={()=>setAskAdjust(true)}><FileClock/>新建调整草稿</button>:<button data-testid="publish-button" onClick={publish}><Send/>发布</button>}</div></div>
{w.status==='adjusting'&&<div className="adjust-banner" data-testid="adjust-banner"><FileClock/><b>调整草稿（基于已冻结的 v{w.baseVersion}）</b><span>原因：{w.draftReason}</span><i>运行中的实例继续读取旧快照，发布后新实例才使用新版本</i></div>}
{locked&&<div className="adjust-banner frozen"><Snowflake/><Lock size={13}/><b>已冻结：权限快照 v{w.version}</b><i>画布、矩阵与配置均不可直接修改；调整只能新建带原因的草稿</i></div>}
<div className="editor-body"><aside className="node-library"><div className="pane-title"><b>节点组件</b><small>点击添加到画布</small></div><div className="node-search">搜索节点组件</div><h4>基础节点</h4>{palette.map(([type,label,desc])=><button key={type} className={'palette '+type} disabled={locked} onClick={()=>add(type)}><span>+</span><div><b>{label}</b><small>{desc}</small></div></button>)}<div className="library-tip"><b>审批节点</b><p>每个审批节点都必须登记审批角色、金额区间和代理审批人，区间重叠或代理成环无法发布。</p></div></aside><section className="editor-center"><div className="canvas-bar"><span>主流程{locked?'（只读快照）':''}</span><span className="spacer"/><button className="icon-btn">−</button><small>100%</small><button className="icon-btn">＋</button></div>{w.nodes.length?<FlowCanvas nodes={w.nodes} edges={w.edges} onNodes={store.updateNodes} onEdges={store.updateEdges} onSelect={store.selectNode} readOnly={locked}/>:<div className="blank-flow"><div>⌘</div><b>从一个开始节点构建流程</b><p>在左侧点击节点组件，将它添加到画布。</p><button onClick={()=>add('start')}><Plus/>添加开始节点</button></div>}</section><ConfigPanel node={selected} locked={locked} roles={store.roles} update={store.updateConfig}/></div>
<section className="issues" data-testid="issues-panel"><div className="issues-head"><b>问题面板</b><span className="error-count" data-testid="error-count">{store.issues.filter(i=>i.level==='error').length} 错误</span><span>{store.issues.filter(i=>i.level==='warning').length} 警告</span><span className="spacer"/><small>发布阻断：区间重叠 · 代理成环 · 离职未交接</small><ChevronDown/></div>{store.issues.length>0&&<div className="issue-list">{store.issues.map((i,k)=>{const conflict=i.conflictNodeId?w.nodes.find(n=>n.id===i.conflictNodeId):undefined;return <button key={i.nodeId+'-'+k} data-testid={'issue-'+(i.kind||'structure')} className={'issue-'+i.level} onClick={()=>i.nodeId!=='flow'&&store.selectNode(i.nodeId)}>{i.level==='error'?<XCircle/>:<CheckCircle2/>}<span className="issue-text"><b>{i.message}</b><small>节点：{w.nodes.find(n=>n.id===i.nodeId)?.data.label||'流程'}{i.role&&<> · 角色：<em>{i.role}</em></>}{i.range&&<> · 区间：<em>{rangeText(i.range)}</em></>}{conflict&&<> · 冲突节点：<em>{conflict.data.label}</em>{i.conflictRange&&<>（{rangeText(i.conflictRange)}）</>}</>}{i.chain&&<> · 代理链：<em>{i.chain.join(' → ')}</em></>}</small></span><span>定位 →</span></button>})}</div>}</section>
{askAdjust&&<ReasonModal title="新建调整草稿" desc={`当前线上运行 v${w.version}（权限快照已冻结），调整将以草稿形式进行`} onCancel={()=>setAskAdjust(false)} onConfirm={reason=>{store.startAdjustment(reason);setAskAdjust(false)}}/>}
</div>}

function ConfigPanel({node,locked,roles,update}:{node?:FlowNode;locked:boolean;roles:{id:string;name:string;status:string;handoverTo?:string}[];update:(id:string,c:Record<string,any>)=>void}){const [saved,setSaved]=useState(false);if(!node)return <aside className="config-panel empty-config"><div>◫</div><b>选择一个节点</b><p>在画布中选择节点以查看和编辑配置。</p></aside>;const c=node.data.config, set=(v:Record<string,any>)=>{update(node.id,v);setSaved(false)};
return <aside className="config-panel" data-testid="config-panel"><div className="config-head"><div><small>{node.type.toUpperCase()} NODE</small><h3>{node.data.label}</h3></div><button className="icon-btn" disabled><Trash2/></button></div>
{locked&&<div className="locked-note"><Lock/><span>当前节点读取自已冻结快照，仅可查看；如需修改请新建调整草稿。</span></div>}
<label>节点名称<input value={node.data.label} readOnly/></label>
{node.type==='approval'&&<><h4>审批人配置</h4><label>审批人来源<select aria-label="审批人来源" disabled={locked} value={c.approverSource||''} onChange={e=>set({approverSource:e.target.value})}><option value="">请选择审批人来源</option><option>直属主管</option><option>固定角色</option><option>指定成员</option><option>表单字段</option></select></label>
<h4>审批矩阵登记</h4>
<div className="matrix-fields" data-testid="matrix-fields"><label>审批角色 *<select aria-label="审批角色" disabled={locked} value={c.role||''} onChange={e=>set({role:e.target.value})}><option value="">请选择审批角色</option>{roles.map(r=><option key={r.id} value={r.name} disabled={r.status==='departed'&&!r.handoverTo}>{r.name}{r.status==='departed'?`（离职${r.handoverTo?'·交接给'+r.handoverTo:'·未交接'}）`:''}</option>)}</select></label>
<div className="form-row"><label>金额下限（元）<input aria-label="金额下限" type="number" disabled={locked} value={c.min??''} onChange={e=>set({min:e.target.value===''?'':Number(e.target.value)})} placeholder="0"/></label><label>金额上限（元）<input aria-label="金额上限" type="number" disabled={locked} value={c.max??''} onChange={e=>set({max:e.target.value===''?null:Number(e.target.value)})} placeholder="空=上不封顶"/></label></div>
<small className="range-hint">登记区间：{rangeText(typeof c.min==='number'&&c.max!==undefined?{min:Number(c.min),max:c.max===null?null:Number(c.max)}:undefined)} · 同一角色区间不得重叠</small>
<label>代理审批人（角色）*<select aria-label="代理审批角色" disabled={locked} value={c.delegateRole||''} onChange={e=>set({delegateRole:e.target.value})}><option value="">请选择代理审批角色</option>{roles.filter(r=>r.status==='active'||r.handoverTo).map(r=><option key={r.id} value={r.name}>{r.name}{r.status==='departed'?'（离职）':''}</option>)}</select></label></div>
<label>审批说明<textarea rows={4} disabled={locked} value={c.instruction||''} onChange={e=>set({instruction:e.target.value})} placeholder="输入审批说明"/></label></>}
{node.type==='condition'&&<><h4>分支规则</h4><label>判断字段<select aria-label="条件字段" disabled={locked} value={c.ruleType||''} onChange={e=>set({ruleType:e.target.value})}><option value="">请选择字段</option><option value="amount">申请金额</option><option value="department">部门</option><option value="attachment">附件</option></select></label><div className="form-row"><label>运算符<select disabled={locked} value={c.operator||'>'} onChange={e=>set({operator:e.target.value})}><option>&gt;</option><option>=</option><option>为空</option></select></label><label>比较值<input aria-label="条件比较值" type="number" disabled={locked} value={c.value||''} onChange={e=>set({value:Number(e.target.value)})}/></label></div><div className="branch-card"><b>分支 1</b><span>满足规则</span></div><div className="branch-card"><b>分支 2</b><span>其他情况</span></div></>}
{node.type==='form'&&<><h4>表单字段</h4>{(c.fields||[]).map((f:any)=><div key={f.id} className="field-chip"><b>{f.label}</b><small>{f.type} · {f.required?'必填':'选填'}</small></div>)}</>}
{node.type==='automation'&&<><h4>本地动作</h4><label>执行动作<select disabled={locked} value={c.action||''} onChange={e=>set({action:e.target.value})}><option>创建工单</option><option>发送 Webhook（模拟）</option><option>写入系统记录</option></select></label></>}
{node.type==='notify'&&<><h4>通知设置</h4><label>通知对象<input disabled={locked} value={c.targets||''} onChange={e=>set({targets:e.target.value})}/></label><label>消息模板<textarea disabled={locked} value={c.template||''} onChange={e=>set({template:e.target.value})}/></label></>}
<div className="config-footer"><span>{saved?<><CheckCircle2/>配置已保存</>:locked?'快照只读':'尚有未保存更改'}</span><button data-testid="save-node-config" disabled={locked} onClick={()=>setSaved(true)}>保存配置</button></div></aside>}
