import {useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {ArrowLeft,Paperclip,RotateCcw,Snowflake} from 'lucide-react';
import {useAppStore} from '../store/useAppStore';

export function Preview(){
 const nav=useNavigate(),{id}=useParams(),store=useAppStore(),w=store.workflows.find(x=>x.id===id)!;
 const form=w.nodes.find(n=>n.type==='form'),condition=w.nodes.find(n=>n.type==='condition');
 const latest=[...w.versions].sort((a,b)=>b.version-a.version)[0];
 const [values,setValues]=useState<Record<string,string>>({});
 const amount=Number(values.amount||0),threshold=Number(condition?.data.config.value||5000),branch=amount>threshold?'高额分支：通知财务审批人':'标准分支：写入系统记录';
 const [submitted,setSubmitted]=useState(false),[launched,setLaunched]=useState<string|null>(null);
 const submit=()=>{setSubmitted(true);if(form?.data.config.fields.some((f:any)=>f.required&&!values[f.id]))return;const iid=store.launchInstance(w.id,values);if(iid)setLaunched(iid);};
 return <div className="preview-page"><header className="preview-header"><button className="icon-btn" onClick={()=>nav(`/workflows/${id}`)}><ArrowLeft/></button><div><b>表单预览</b><small>{w.name} · 提交即按最新发布快照发起实例</small></div><span className="spacer"/>{latest&&<span className="snapshot-badge large"><Snowflake width={13}/>新实例将使用 v{latest.version}</span>}<button className="secondary" onClick={()=>{setValues({});setLaunched(null);setSubmitted(false)}}><RotateCcw/>重置</button><button data-testid="simulate-submit" onClick={submit}>模拟提交并发起实例</button></header>
 <div className="preview-stage"><section className="form-preview"><div className="form-cover"><small>{w.domain} / 申请表单</small><h1>{form?.data.label||'业务申请'}</h1><p>请完整填写以下信息，带 * 的字段为必填项。</p></div><div className="form-body">{(form?.data.config.fields||[]).map((f:any)=><label key={f.id}>{f.label}{f.required&&<em>*</em>}{f.type==='attachment'?<div className="upload"><Paperclip/><b>拖入文件或点击上传</b><small>支持 PDF、DOCX、PNG，单个文件不超过 20MB</small></div>:f.type==='text'?<textarea aria-label={f.label} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} rows={5} placeholder="请输入详细说明（最多 2,000 字）"/>:<div className={f.type==='amount'?'money-input':''}>{f.type==='amount'&&<span>¥</span>}<input aria-label={f.label} type={f.type==='amount'||f.type==='number'?'number':f.type==='date'?'date':'text'} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} placeholder={f.type==='amount'?'0.00':'请输入'}/></div>}{submitted&&f.required&&!values[f.id]&&<small className="field-error">此字段为必填项</small>}</label>)}</div></section>
 <aside className="simulation"><h3>条件分支模拟</h3><p>表单字段变化会实时计算流程走向。</p><div className="sim-rule"><small>当前规则</small><b>申请金额 &gt; ¥{threshold.toLocaleString()}</b></div><div className={'sim-result '+(amount>threshold?'high':'normal')} data-testid="branch-result"><small>模拟结果</small><b>{branch}</b><p>当前输入：¥{amount.toLocaleString(undefined,{minimumFractionDigits:2})}</p></div><div className="sim-path"><span className="done">提交申请</span><i>↓</i><span className="done">直属主管审批</span><i>↓</i><span className="active">{amount>threshold?'高额通知':'记录系统'}</span></div>
  <div className="launch-result" data-testid="launch-result">{launched?<><b>✓ 实例 {launched} 已发起</b><small>已锁定最新权限快照 v{latest!.version}，之后再发布新版本也不影响该实例</small><button className="secondary" onClick={()=>nav('/monitor?instance='+launched)}>去运行监控查看</button></>
   :w.versions.length===0?<b className="missing">该流程从未发布成功（存在矩阵冲突），不能发起实例</b>:<small>提交表单后将按 v{latest!.version} 快照发起运行实例，新实例使用新版本、旧实例继续读旧快照</small>}</div>
 </aside></div></div>;
}
